steps:
  # build base image with requirements
  - name: "eu.gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME/base_image:$COMMIT_SHA"
      - "--file"
      - "$_DOCKERFILE_BASE"
      - "$DOCKERFILE"
  # push base image with requirements
  - name: "eu.gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME/base_image:$COMMIT_SHA"
  # build the container image
  - name: "eu.gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "BASE=gcr.io/$PROJECT_ID/$_SERVICE_NAME/base_image:$COMMIT_SHA"
      - "--tag"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "$_DOCKERFILE"
  # push the app container image to Container Registry
  - name: "eu.gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"]
  # Deploy app container image to Cloud Run
  - name: "eu.gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
images:
  - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
