steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "_BASE_URL=$_BASE_URL"
      - "--build-arg"
      - "_AIRTABLE_API_KEY=$_AIRTABLE_API_KEY"
      - "--build-arg"
      - "_AIRTABLE_BASE_ID=$_AIRTABLE_BASE_ID"
      - "--build-arg"
      - "_GOOGLE_CLOUD_PROJECT=$_GOOGLE_CLOUD_PROJECT"
      - "--build-arg"
      - "_SUB_PUB_TOPIC_NAME=$_SUB_PUB_TOPIC_NAME"
      - "--tag"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "$_DOCKERFILE"
  # push the app container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"]
  # Deploy app container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
images:
  - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
