steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "$_DOCKERFILE"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"
  # push the app container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"]
  # Deploy app container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image"
      - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
images:
  - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
  - "eu.gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"
